
name: Deploy GitHub Pages

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout --orphan gh-pages
          cat assets/style/v.css > v.css
          cat assets/style/header.css >> v.css
          cat assets/style/card.css >> v.css
          cat assets/style/player.css >> v.css
          curl -o _site/v.min.css -X POST -s --data-urlencode 'input@v.css' https://cssminifier.com/raw
          cat assets/script/player.js > v.js
          curl -o _site/v.min.js -X POST -s --data-urlencode 'input@v.js' https://javascript-minifier.com/raw
          find . -mindepth 1 -maxdepth 1 -type f,d ! -name .git ! -name _site -print | xargs rm -rf
          find _site -mindepth 1 -maxdepth 1 -type f,d ! -name .git ! -name _site -print | xargs -I {} mv -f '{}' .
          rm -rf _site
          git add --all
          git commit -m "deploy to gh-pages"
          git push origin gh-pages -f
